### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by jwyune** [STMicroelectronics/meta-st-stm32mpu-app-aws#1]
First of all, thanks a lot for uploading this.

I followed all the steps explained in Wiki, and there are few issues that need to be address.

1. [TPM2 Token](https://github.com/STMicroelectronics/meta-st-stm32mpu-app-aws#tpm2-token-intialisation)
When I executed the following command, I get an error saying: "no module named 'pyasn1-modules'"
`Board $>./tpm2_ptool.py init --primary-auth=123456 --path=$TPM2_PKCS11_STORE`

I am not really familiar with TPM2, and AWS IoT Greengrass should work without it, but it would be nice if we can fix the issue.

2. There is a version-incompatibility issue with GGC and Python. The image as it is provides GGC 1.10.1 with Python 3.8. However, it needs to be one of two combinations: GGC 1.11.0 with Python 3.8 or GGC 1.10.1 with Python 3.7.

I am working on upgrading GGC to 1.11.0. Is there a way to downgrade Python to 3.7?

**Comment by pywtk** [comment]
Hi! I too am seeing issue 1. How did you resolve it?
